apiDir: "../search-api-api/src/main/java"
apiPackagePath: "custom.search.api"
generateGraphQL: false
application:
    baseURI: "/search-api"
    className: "SearchApiApplication"
    name: "CustomSearchApi"
    security:
        basicAuth: true
        guestAllowed: true
        oAuth2: true
author: "ligasm"
